app_name: PsyInf Knowledge Pooling Tool
page_title: PsyInf Knowledge
documentation_url: ''
source_code_url: https://hub.psychoinformatics.de/www/pool.psychoinformatics.de-ui
app_theme:
  link_color: '#ffa200'
  hover_color: '#ffa200'
  active_color: '#ffa201'
  visited_color: '#ffa201'
  panel_color: '#333333'
  logo: logo.png
shapes_url: https://concepts.datalad.org/s/demo-rse-group/unreleased.shacl.ttl
use_default_shapes: false
data_url: ''
use_default_data: false
class_url: https://concepts.datalad.org/s/demo-rse-group/unreleased.owl.ttl
use_default_classes: false
id_iri: https://concepts.datalad.org/s/things/v1/pid
id_autogenerate:
  # this uses the namespace `xyzrsens`, because that is defined in the demo
  # schema we are using right now. Eventually, this should all migrate
  # to a dedicated schema and to a dedicated "psyinf" namespace
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZAgentRole:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: agent-roles/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZBibliographicType:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: bibliographic-types/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZCompetition:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: competitions/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZCompetitionType:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: competition-types/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZConcept:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: concepts/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZConvention:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: conventions/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDataset:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: datasets/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDataType:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: datatypes/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDistribution:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: distributions/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDocument:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: documents/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZGrant:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: grants/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZInstrument:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: instruments/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZInstrumentType:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: instrument-types/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZObjective:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: objectives/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZOrganization:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: organizations/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPerson:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: persons/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZProject:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: projects/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPublication:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: publications/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPublicationVenue:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: publication-venues/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZRule:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: rules/
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZTopic:
    id_autogenerate_prefix: xyzrsens
    id_autogenerate_prepend: topic/
id_resolves_externally:
  - bibo
  - doi
  - geodata
  - gepris
  - IAO
  - ISSN
  - marcrel
  - obo
  - orcid
  - ror
  - rrid
  - spdxlic
show_shapes_wo_id: false
show_all_fields: false
show_classes: []
show_classes_with_prefix:
  - xyzrse
hide_classes: []
hide_classes_with_prefix: []
no_edit_classes:
  - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZAgentRole
  - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZBibliographicType
allow_copy_record_urls: true
allow_edit_instances:
  - https://concepts.datalad.org/s/identifiers/unreleased/Checksum
  - https://concepts.datalad.org/s/identifiers/unreleased/ComputedIdentifier
  - https://concepts.datalad.org/s/identifiers/unreleased/DOI
  - https://concepts.datalad.org/s/identifiers/unreleased/IssuedIdentifier
  - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZCommunication
  - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDocumentExchange
  - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZInfluence
  - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPersonAttribution
editor_selection:
  sh:datatype:
    xyzrse:flexdate: W3CISO8601DatePickerEditor
    w3ctr:NOTE-datetime: W3CISO8601DatePickerEditor
  shaclvue:gitAnnexUpload:
    'true': InstancesUploadEditor
component_config:
  W3CISO8601YearMonthEditor:
    yearStart: 1990
    yearEnd: 2028
  W3CISO8601DateTimeEditor:
    yearStart: 1990
    yearEnd: 2028
  InstancesUploadEditor:
    xyzrse:XYZDocument:
      pid_template: psyinfdoc:{_randomUUID}
      ttl_template: content:DocumentUploadTemplate
  InstancesSelectEditor:
    fetchingsRecordsText: Fetching records...
    dlidentifiers:Identifier:
      show_classes: []
      show_classes_with_prefix:
        - dlidentifiers
        - xyzrse
      hide_classes: []
      hide_classes_with_prefix: []
content:
  DocumentUploadTemplate:
    url: DocumentUploadTemplate.ttl
class_name_display: name
display_name_autogenerate:
  dlidentifiers:Identifier: '{dlidentifiers:notation} ({dlidentifiers:schema_agency} {dlidentifiers:creator})'
  dlidentifiers:Checksum: '{dlidentifiers:creator}:{dlidentifiers:notation}'
  dlidentifiers:DOI: 'DOI: {dlidentifiers:notation}'
  xyzrse:ORCID: 'ORCID: {dlidentifiers:notation}'
  dlprovmx:End: '{dltemporalmx:at_time}'
  dlprovmx:Start: '{dltemporalmx:at_time}'
  dlprovmx:Usage: '{rdf:object} ({dlrelationsmx:roles})'
  dlprovmx:Association: '{rdf:object} ({dlrelationsmx:roles})'
  xyzrse:XYZAccolade: '{dlcommonmx:title}'
  xyzrse:XYZAgentRole: '{skos:prefLabel}'
  xyzrse:XYZAssociation: '{rdf:object} ({dlrelationsmx:roles})'
  xyzrse:XYZCommunication: '{rdf:object} ({dlrelationsmx:roles})'
  xyzrse:XYZConvention: '{dlcommonmx:short_name}'
  xyzrse:XYZDataset: '{dlcommonmx:title}'
  xyzrse:XYZDocument: '{dlcommonmx:title}'
  xyzrse:XYZDocumentExchange: '{rdf:object} ({dlrelationsmx:roles})'
  xyzrse:XYZEnd: '{dltemporalmx:at_time}'
  xyzrse:XYZGenesis: '{dlcommonmx:name}'
  xyzrse:XYZGrant: '{dlcommonmx:title}'
  xyzrse:XYZInfluence: '{rdf:object} ({dlrelationsmx:roles})'
  xyzrse:XYZInstrument: '{dlcommonmx:name}'
  xyzrse:XYZNamedDistributionPart: '{dlspatialmx:locator}'
  xyzrse:XYZObjective: '{dlcommonmx:title}'
  xyzrse:XYZOrganization: '{dlcommonmx:name}'
  xyzrse:XYZPerson: '{dlsocialmx:family_name}, {dlsocialmx:given_name}'
  xyzrse:XYZPersonAttribution: '{rdf:object} ({dlrelationsmx:roles})'
  xyzrse:XYZProject: '{dlcommonmx:title}'
  xyzrse:XYZPublication: '{dlcommonmx:title}'
  xyzrse:XYZPublicationVenue: '{dlcommonmx:title}'
  xyzrse:XYZStart: '{dltemporalmx:at_time}'
  xyzrse:XYZSubject: '{dlcommonmx:name}'
  xyzrse:XYZUsage: '{rdf:object} ({dlrelationsmx:roles})'
display_name_autogenerate_placeholder:
  default: '?'
  dlidentifiers:creator: ''
  dlidentifiers:schema_agency: ''
use_service: true
use_token: true
token_info: Please contact Michael Hanke at m.hanke@fz-juelich.de for credentials.
token_info_url: ''
service_base_url:
  - url: https://pool.psychoinformatics.de/api/protected/
    type: write
  - url: https://pool.psychoinformatics.de/api/public/
    type: read
service_constrained_search:
  min_characters: 3
service_endpoints:
  post-record: record/{name}?format=ttl
  get-record: record?pid={curie}&format=ttl
  get-records: records/{name}?format=ttl
  get-paginated-records: records/p/{name}?format=ttl&size=100&page={page_number}
  get-paginated-records-constrained: records/p/{name}?format=ttl&matching=%25{match_string}%25&size=100&page={page_number}
service_fetch_before:
  get-record: []
  get-records:
    - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZAgentRole
    - https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPerson
use_gitannex_p2phttp: true
gitannex_p2phttp_config:
  base_url: https://hub.edu.datalad.org/git-annex-p2phttp/git-annex
  annex_uuid: 966d1459-89e6-4eba-b777-33b31c664d66
  client_uuid: shacl-vue
prefixes:
  psyinf: https://psychoinformatics.de/ns/
  psyinfroot: https://psychoinformatics.de/
  psyinfdoc: https://psychoinformatics.de/ns/documents/
  shaclvue: https://concepts.datalad.org/ns/shaclvue/
footer_links: []
class_icons:
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZAccolade: mdi-medal
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZAgentRole: mdi-function
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZAssociation: mdi-account-switch
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZBibliographicType: mdi-newspaper
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZCommunication: mdi-message-text-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZCompetition: mdi-podium-gold
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZCompetitionType: mdi-podium
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZConcept: mdi-shape-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZConvention: mdi-script-text-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDataItem: mdi-file-document-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDataType: mdi-tape-measure
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDataset: mdi-database
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDistribution: mdi-folder-arrow-right-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDistributionPartType: mdi-folder-file-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDistributionType: mdi-folder-table-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDocument: mdi-file-document-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZDocumentExchange: mdi-file-arrow-up-down-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZEnd: mdi-clock-end
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZGenesis: mdi-creation
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZGrant: mdi-cash-100
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZInfluence: mdi-arrow-decision
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZInstrument: mdi-microscope
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZInstrumentType: mdi-beaker-question-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZNamedDistributionPart: mdi-folder-text-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZObjective: mdi-bullseye-arrow
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZOrganization: mdi-account-group
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPerson: mdi-face-man
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPersonAttribution: mdi-clipboard-account-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZProject: mdi-briefcase-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPublication: mdi-newspaper-variant-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZPublicationVenue: mdi-office-building-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZRule: mdi-gavel
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZStart: mdi-clock-start
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZStudy: mdi-school-outline
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZSubject: mdi-account-search
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZSubjectType: mdi-tag-search
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZTopic: mdi-book-information-variant
  https://concepts.datalad.org/s/demo-rse-group/unreleased/XYZUsage: mdi-format-list-checks
  https://concepts.datalad.org/s/identifiers/unreleased/Checksum: mdi-file-check-outline
  https://concepts.datalad.org/s/identifiers/unreleased/ComputedIdentifier: mdi-pound-box-outline
  https://concepts.datalad.org/s/identifiers/unreleased/DOI: mdi-identifier
  https://concepts.datalad.org/s/identifiers/unreleased/Identifier: mdi-identifier
  https://concepts.datalad.org/s/identifiers/unreleased/IssuedIdentifier: mdi-identifier
  https://concepts.datalad.org/s/demo-rse-group/unreleased/ORCID: mdi-identifier
  https://concepts.datalad.org/s/prov-mixin/unreleased/Association: mdi-account-switch
  https://concepts.datalad.org/s/prov-mixin/unreleased/Communication: mdi-message-text-outline
  https://concepts.datalad.org/s/prov-mixin/unreleased/End: mdi-clock-end
  https://concepts.datalad.org/s/prov-mixin/unreleased/Start: mdi-clock-start
  https://concepts.datalad.org/s/prov-mixin/unreleased/Usage: mdi-format-list-checks
  https://concepts.datalad.org/s/things/v1/Annotation: mdi-tag-outline
  https://concepts.datalad.org/s/things/v1/AttributeSpecification: mdi-playlist-check
  https://concepts.datalad.org/s/things/v1/Statement: mdi-comment-text-outline
