# --------------------
# General app settings
# --------------------
app_name: PsyInf Knowledge Pooling Tool
app_name_starter: PsyInf Knowledge Kickstarter
documentation_url: ''
external_config_url: config_default_xyzri.yaml
page_title: PsyInf Knowledge
source_code_url: https://hub.psychoinformatics.de/www/pool.psychoinformatics.de-ui

# -------
# Content
# -------
content:
  add-record:
    url: templates/add-record.nunjucks.ttl
  person-depiction-upload:
    url: templates/person-depiction-upload.nunjucks.ttl
  DocumentUploadTemplate:
    url: templates/DocumentUploadTemplate.ttl
  DOIImportWizardTemplate:
    url: templates/DOIImportWizardTemplate.nunjucks.ttl
  DOIWizardTemplate:
    url: templates/DOIWizardTemplate.ttl
  DOIlogo:
    url: DOI_logo_24.svg
  file-upload-template:
    url: templates/file-upload.ttl
  orcid-logo:
    url: orcid_logo_24.svg

# --------------
# Theme settings
# --------------
app_theme:
  link_color: '#ffa200'
  hover_color: '#ffa200'
  active_color: '#ffa201'
  visited_color: '#ffa201'
  panel_color: '#333333'
  logo: logo.png

# --------------------------
# Application inputs sources
# --------------------------
# All from external_config_url

# -------------------
# Identifier settings
# -------------------
# All from external_config_url

# ------------
# UI behaviour
# ------------
component_config:
  InstancesUploadEditor:
    dlthings:Thing:
      pid_template: datalad:aa2b2132-f3f1-4d62-b245-d9717722897e/uuid/{_randomUUID}
      ttl_template: content:DocumentUploadTemplate
  NodeShapeViewer:
    hideBackLinks:
      - dlthings:AnnotationTag
      - xyzri:AgentRole
    specialButtons:
      ORCID:
        slot: dcterms:identifier
        match:
          - key: rdf:type
            val: xyzri:ORCID
        return: skos:notation
        template: 'https://orcid.org/{return}'
        icon: content:orcid-logo
        tooltip: Visit ORCID page
      DOI:
        slot: dcterms:identifier
        match:
          - key: rdf:type
            val: dlthings:DOI
        return: skos:notation
        template: 'https://doi.org/{return}'
        icon: content:DOIlogo
        tooltip: Go to DOI
      DownloadUrl:
        slot: dlthings:characterized_by
        match:
          - key: rdf:type
            val: dlthings:Statement
          - key: rdf:predicate
            val: dcat:downloadUrl
        return: rdf:object
        template: '{return}'
        icon: mdi-download
        tooltip: Download
      Homepage:
        slot: dlthings:attributes
        match:
          - key: rdf:type
            val: dlthings:AttributeSpecification
          - key: rdf:predicate
            val: foaf:homepage
        return: rdf:value
        template: '{return}'
        icon: mdi-home
        tooltip: Homepage
      Documentation:
        slot: dlthings:attributes
        match:
          - key: rdf:type
            val: dlthings:AttributeSpecification
          - key: rdf:predicate
            val: obo:NGBO_6000416
        return: rdf:value
        template: '{return}'
        icon: mdi-text-box
        tooltip: Documentation
      SourceCodeRepo:
        slot: dlthings:attributes
        match:
          - key: rdf:type
            val: dlthings:AttributeSpecification
          - key: rdf:predicate
            val: obo:APOLLO_SV_00000488
        return: rdf:value
        template: '{return}'
        icon: mdi-code-block-tags
        tooltip: Source code
filter_records_by:
  - dlthings:short_name
show_classes:
  - dlthings:AnnotationTag
  - dlthings:Convention
  # must list the next to get all identifiers to show
  - dlthings:Identifier
  - dlthings:DOI
  - dlthings:ISSN
  - dlthings:ORCID
  - dlthings:Rule
  - dlthings:Property
#no_edit_classes:
#  - xyzri:XYZBibliographicType
priority_classes:
  - class: dlthings:Thing
    icon: mdi-view-list
    title: All
    include_subclasses: true
wizard_editors:
  AddRecordWizard:
    name: Quick-Add New Record
    tooltip: Quick Add
    icon: mdi-plus-box
    description: Add the display name and description and then hit *Save*
    inputs:
      - prop: name
        name: Display name
        description: The display name of the new record
        type: text
        placeholder: 'My record title'
        required: true
      - prop: description
        name: Description
        description: The description of the new record
        type: text-paragraph
        placeholder: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod...'
    template: content:add-record
  DepictionUploadWizard:
    name: Depiction Upload Wizard
    tooltip: Upload a depiction
    icon: mdi-account-box-outline
    description: Upload an image of the person and hit *Save*
    inputs:
      - prop: file
        name: File
        type: upload
        required: true
    template: content:person-depiction-upload
  DOIWizard:
    name: DOI Wizard
    tooltip: Add a Digital Object Identifier
    icon: content:DOIlogo
    description: Enter the 'Notation' field and hit *Save* in order to create a DOI record
    inputs:
      - prop: notation
        name: Notation
        description: This is the unique DOI identifier text following the creator URI (typically 'http://doi.org/')
        type: text
        placeholder: 'example: 10.21105/joss.03262'
        required: true
        # pattern: 
        # default:
    template: content:DOIWizardTemplate
  DOIImportWizard:
    name: DOI Import Wizard
    tooltip: Import a publication via DOI
    icon: mdi-import
    description: >-
      Enter the 'DOI' field and hit *Import* in order to import metadata.
      This will prepopulate editable fields such as *Title* and *Authors*.
      An attempt is made to match individual imported *Author*s with known
      *Person* records via ORCID identifiers. These matches can be accepted
      as is without editing. The dropdown next to each imported and unmatched
      author can be used to manually identify the correct associated Person
      record. Also, additional authors can be added to the list. If no Person
      record is selected for any given author in the list, a new Person record
      will be created with a random and unique identifier, associated with the
      entered given and family name.
    component: doi:DOIFetcher
    inputs:
      - prop: title
        type: text
      - prop: abstract
        type: text-paragraph
      - prop: authors
        type: object
        multi_valued: true
        inputs:
          - prop: pid
            type: text
          - prop: given_name
            type: text
          - prop: family_name
            type: text
          - prop: role
            type: select
    template: content:DOIImportWizardTemplate
  FileUploadWizard:
    name: File Upload Wizard
    tooltip: Upload a file
    icon: mdi-file-upload-outline
    description: Upload a file and hit *Save*
    inputs:
      - prop: file
        name: File
        type: upload
        required: true
    template: content:file-upload-template
wizard_editor_selection:
  _classes:
    - AddRecordWizard
  xyzri:XYZPerson:
    _record:
      - DepictionUploadWizard
  xyzri:XYZPublication:
    _class:
      - DOIImportWizard
    _record:
      - DOIWizard
  _slots:
    dlthings:distributions:
      _record:
        - FileUploadWizard

# -----------------------
# Service API integration
# -----------------------
service_base_url:
  - url: http://127.0.0.1:8111/protected/
    type: write
  - url: http://127.0.0.1:8111/public/
    type: read
token_info: Please contact Michael Hanke at m.hanke@fz-juelich.de for credentials, or log in / refresh token via the Psychoinformatics Hub.
token_info_url: ''
use_service: true
use_token: true
service_fetch_before:
  get-records:
    - xyzri:XYZActivity
    - xyzri:XYZAgentRole
    - xyzri:XYZBibliographicType
    - xyzri:XYZCompetitionType
    - xyzri:XYZDepictionType
    - xyzri:XYZInstrumentType
    - xyzri:XYZPerson
    - xyzri:XYZTopic

# ----------------
# Special features
# ----------------
gitannex_p2phttp_config:
  base_url: https://hub.psychoinformatics.de/git-annex-p2phttp/git-annex
  annex_uuid: f1a8ef1c-6d8a-40e3-970f-4634390d961f
  client_uuid: 2e7a7d75-f2ed-11f0-90a9-dc97ba1c2528
use_gitannex_p2phttp: true

gitannex_p2phttp_config_wizard:
  client_uuid: 2e7a7d75-f2ed-11f0-90a9-dc97ba1c2528
  targets:
    - name: Psychoinformatics Hub
      base_url: https://hub.psychoinformatics.de/git-annex-p2phttp/git-annex
      repositories:
        - name: Public uploads
          annex_uuid: cedde37c-416a-41fd-87e0-4ac100df4bf7
        - name: Private uploads
          annex_uuid: f1a8ef1c-6d8a-40e3-970f-4634390d961f

oidc:
  - name: Psychoinformatics Hub
    base_url: https://hub.psychoinformatics.de
    auth_endpoint: login/oauth/authorize
    token_endpoint: login/oauth/access_token
    client_id: 0d8a5a00-6aed-4cee-9317-baeb9888b4b2
    redirect_uri: https://pool.psychoinformatics.de/ui/auth/oidc-callback.html
    response_type: code
    code_challenge_method: S256
    grant_type: authorization_code

# -------------
# Update shapes
#--------------
update_shapes_default:
  _all_property_shapes:
    dlthings:pid:
      sh:minCount: 1
