# --------------------
# General app settings
# --------------------
app_name: PsyInf Knowledge Pooling Tool
documentation_url: ''
external_config_url: https://hub.psychoinformatics.de/orinoco/assets/raw/branch/psyinf-config/shacl-vue/config_default_xyzri.yaml
page_title: PsyInf Knowledge
source_code_url: https://hub.psychoinformatics.de/www/pool.psychoinformatics.de-ui

# -------
# Content
# -------
content:
  DocumentUploadTemplate:
    url: templates/DocumentUploadTemplate.ttl
  DOIWizardTemplate:
    url: templates/DOIWizardTemplate.ttl
  DOIlogo:
    url: https://hub.psychoinformatics.de/datalink/assets/raw/branch/main/shacl-vue/DOI_logo_24.svg
  file-upload-template:
    url: templates/file-upload.ttl
  orcid-logo:
    url: https://hub.psychoinformatics.de/datalink/assets/raw/branch/main/shacl-vue/orcid_logo_24.svg

# --------------
# Theme settings
# --------------
app_theme:
  link_color: '#ffa200'
  hover_color: '#ffa200'
  active_color: '#ffa201'
  visited_color: '#ffa201'
  panel_color: '#333333'
  logo: logo.png

# --------------------------
# Application inputs sources
# --------------------------
# All from external_config_url

# -------------------
# Identifier settings
# -------------------
# All from external_config_url

# ------------
# UI behaviour
# ------------
component_config:
  InstancesUploadEditor:
    dlthings:Thing:
      pid_template: datalad:aa2b2132-f3f1-4d62-b245-d9717722897e/uuid/{_randomUUID}
      ttl_template: content:DocumentUploadTemplate
  NodeShapeViewer:
    hideBackLinks:
      - dlthings:AnnotationTag
      - xyzri:AgentRole
    specialButtons:
      ORCID:
        slot: dcterms:identifier
        match:
          - key: rdf:type
            val: xyzri:ORCID
        return: skos:notation
        template: 'https://orcid.org/{return}'
        icon: content:orcid-logo
        tooltip: Visit ORCID page
      DOI:
        slot: dcterms:identifier
        match:
          - key: rdf:type
            val: dlthings:DOI
        return: skos:notation
        template: 'https://doi.org/{return}'
        icon: content:DOIlogo
        tooltip: Go to DOI
      DownloadUrl:
        slot: dlthings:characterized_by
        match:
          - key: rdf:type
            val: dlthings:Statement
          - key: rdf:predicate
            val: dcat:downloadUrl
        return: rdf:object
        template: '{return}'
        icon: mdi-download
        tooltip: Download
      Homepage:
        slot: dlthings:attributes
        match:
          - key: rdf:type
            val: dlthings:AttributeSpecification
          - key: rdf:predicate
            val: foaf:homepage
        return: rdf:value
        template: '{return}'
        icon: mdi-home
        tooltip: Homepage
filter_records_by:
  - dlthings:short_name
show_classes:
  - dlthings:AnnotationTag
  - dlthings:Convention
  # must list the next to get all identifiers to show
  - dlthings:Identifier
  - dlthings:DOI
  - dlthings:ISSN
  - dlthings:ORCID
  - dlthings:Rule
  - dlthings:Property
#no_edit_classes:
#  - xyzri:XYZBibliographicType
priority_classes:
  - class: dlthings:Thing
    icon: mdi-view-list
    title: All
    include_subclasses: true
wizard_editors:
  DOIWizard:
    name: DOI Wizard
    tooltip: Add a Digital Object Identifier
    icon: content:DOIlogo
    description: Enter the 'Notation' field and hit *Save* in order to create a DOI record
    inputs:
      - prop: notation
        name: Notation
        description: This is the unique DOI identifier text following the creator URI (typically 'http://doi.org/')
        type: text
        placeholder: 'example: 10.21105/joss.03262'
        required: true
        # pattern: 
        # default:
    template: content:DOIWizardTemplate
  FileUploadWizard:
    name: File Upload Wizard
    tooltip: Upload a file
    icon: mdi-file-upload-outline
    description: Upload a file and hit *Save*
    inputs:
      - prop: file
        name: File
        type: upload
        required: true
    template: content:file-upload-template
wizard_editor_selection:
  xyzri:XYZPublication:
    _record:
      - DOIWizard
  _slots:
    dlthings:distributions:
      _record:
        - FileUploadWizard

# -----------------------
# Service API integration
# -----------------------
service_base_url:
  - url: https://pool.psychoinformatics.de/api/protected/
    type: write
  - url: https://pool.psychoinformatics.de/api/public/
    type: read
token_info: Please contact Michael Hanke at m.hanke@fz-juelich.de for credentials.
token_info_url: ''
use_service: true
use_token: true
service_fetch_before:
  get-records:
    - xyzri:XYZAgentRole
    - xyzri:XYZDepictionType
    - xyzri:XYZPerson

# ----------------
# Special features
# ----------------
gitannex_p2phttp_config:
  base_url: https://hub.psychoinformatics.de/git-annex-p2phttp/git-annex
  annex_uuid: f1a8ef1c-6d8a-40e3-970f-4634390d961f
  client_uuid: 2e7a7d75-f2ed-11f0-90a9-dc97ba1c2528
use_gitannex_p2phttp: true

gitannex_p2phttp_config_wizard:
  client_uuid: 2e7a7d75-f2ed-11f0-90a9-dc97ba1c2528
  targets:
    - name: Psychoinformatics Hub
      base_url: https://hub.psychoinformatics.de/git-annex-p2phttp/git-annex
      repositories:
        - name: Private uploads
          annex_uuid: f1a8ef1c-6d8a-40e3-970f-4634390d961f
        - name: Public uploads
          annex_uuid: cedde37c-416a-41fd-87e0-4ac100df4bf7
